name: quickstart
modulepath: libs
downloadpath: libs
repo: https://github.com/inmanta/
description: A quickstart project that installs a drupal website.
requires:
    - apache ~= 0.3.1
    - drupal ~= 0.7.1
    - ip ~= 1.0.0
    - mysql ~= 0.6.0
    - redhat ~= 0.8.0
    - web ~= 0.2.2
